### ISSUE TITLE
Normalize to 0..1 grid?

### ISSUE THREAD

**Issue by yarpoplar** [mio3io/mio3_uv#1]
Such a great addon, thank you for making this!
All I want is to ask for one feature - can you please add a Normalize function just like in Maya? https://help.autodesk.com/view/MAYACRE/ENU/?guid=GUID-3FDE8873-2169-412F-9A07-26F44E52C5DD
With that option we can fit unwrapped rectangle to the full grid and with this addition your addon would be a great fit for VFX artists out there as well!

**Comment by mio3io** [comment]
It's not perfect, but I implemented it based on the documentation and other add-ons. I haven't used this function much in character modeling, so I'm not sure if the results are what you'd expect.

**Comment by yarpoplar** [comment]
Works like a charm, thank you very much!

![blender_gUfhbVFnGw](https://github.com/user-attachments/assets/9a687e9c-d8e2-4990-969f-0691fce9f867)
