### ISSUE TITLE
Addition of a texel density calculator

### ISSUE THREAD

**Issue by SlincHD** [mio3io/mio3_uv#10]
hello! i found mio3 UV over the blender extension and it is realy good
tho what i am missing is a texel density calculator wich is a very important step in the making of UV's for Game creation so if it was posible could you add a texcel density calculator?

**Comment by mio3io** [comment]
https://extensions.blender.org/add-ons/texel-density-checker/

Sorry, but I don't have any plans to implement this in this addon at the moment, because I already have several addons that I personally find useful.
