### ISSUE TITLE
Issue with copy

### ISSUE THREAD

**Issue by Antao98** [mio3io/mio3_uv#11]
Hello,

I'm having some issues getting the copy UV functionality to work. I'm using Blender 4.2.3 and I can't seem to get it to work, even with simple meshes/UVs. 

Could you help me please?

**Comment by mio3io** [comment]
This feature uses standard Blender functionality, so it depends on Blender's implementation.
https://docs.blender.org/manual/en/latest/modeling/meshes/uv/editing.html#paste-uvs

**Comment by Antao98** [comment]
Alright, thank you so much for the quick answer. I'll see what I can do :)
