### ISSUE TITLE
Not working at 4.2.3

### ISSUE THREAD

**Issue by nakano52** [mio3io/mio3_uv#12]
日本語で失礼します
バージョン4.2.3(PortableApp版)でMio3 UVのインストールをしようとしたところ、このようなエラーメッセージが出て、アドオンを使用することができませんでした
![報告](https://github.com/user-attachments/assets/7341e6ec-0ddd-4902-9f54-d88dd6adcae6)
こちらの環境は
Windows 10 Pro 64bit
AMD Ryzen 9 7900
RAM : 64.0 GB
GeForce RTX 4090
Blenderバージョン : 4.2.3(PortableApp版)
です
確認の方、よろしくお願いします

**Comment by mio3io** [comment]
ざっくり読んだところ、Pythonのnumpyモジュールが読み込めないようです。

ブレンダー上のスクリプトエディタで空テキストを作って、次のコードを実行▶すれば手動でインストールすることもできます

```
import bpy
import subprocess
import sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "numpy"])
```

https://stackoverflow.com/questions/68440931/install-numpy-for-blender
このへんのポストも参考になるかもしれません。

**Comment by nakano52** [comment]
ありがとうございます
numpyを更新したところ動きました
どうやらこちらの環境に不備があったようです
問題が解決したので閉めさせていただきます
