### ISSUE TITLE
Publish your add-on to the Blender Extensions Platform

### ISSUE THREAD

**Issue by xan2622** [mio3io/mio3_uv#3]
Hi. 

As you may already know, add-ons and themes can now be uploaded to the [Blender Extensions Platform](https://extensions.blender.org/).

Related topics:
https://extensions.blender.org/about/
https://docs.blender.org/manual/en/latest/advanced/extensions/getting_started.html#how-to-create-extensions
https://code.blender.org/2024/05/extensions-platform-beta-release/
https://devtalk.blender.org/t/changes-to-add-on-and-themes-bundling-4-2-onwards/34593

I think it would be really cool (and convenient) if your add-on was available on the Blender Extensions Platform. It would help Blender users discover and download your add-on more easily.

Have you ever considered uploading your add-on on this new website?
Thanks in advance.

**Comment by mio3io** [comment]
Thank you!
This add-on has been submitted to Extensions and is currently undergoing review.
