### ISSUE TITLE
角部分のpaddingについて

### ISSUE THREAD

**Issue by mill101** [mio3io/mio3_uv#4]
とても素晴らしいadd-onです。
特にpreview paddingは正に探していた機能でした。
リクエストが可能ならばなのですが
優先度順に

1.添付図上のように角部分の頂点は指定ピクセルよりpaddingが少なくなっています。
頂点両側の辺、直角方向へ伸ばした線と線の中間方向に指定ピクセル分paddingを広くとることはできないでしょうか。（図下）

2.他人のデータを確認する際、目視でpaddingが足りないところを確認するのは大変なため、paddingの青線同士が重なった場合、その周辺の頂点を選択する機能は可能でしょうか。

宜しくお願いします。
![interporate](https://github.com/user-attachments/assets/402bd54c-f55f-4e13-b41f-d3c3a04b043b)

**Comment by mio3io** [comment]
ありがとうございます。

パディング表示については満足のいく状態ではないことを理解しておりこの機能を含めるかどうか非常に悩んだのですが、個人的には許容範囲だったため妥協した感じです。

試行錯誤してはいるのですが、GPUモジュール自体扱いに慣れていなくてなかなかうまくいかないようです。
将来的に改善する可能性がありますが、今は目安程度にご利用いただければと思います。

**Comment by mill101** [comment]
承知しました。
今の状態でも十分満足できる素晴らしい完成度です。
ご連絡ありがとうございました。
