### ISSUE TITLE
realtimeオンでクラッシュ

### ISSUE THREAD

**Issue by mill101** [mio3io/mio3_uv#5]
お疲れ様です。
不具合報告です。

realtimeをオンにして頂点を移動するとクラッシュしました。
polySource add-onをオフにするとなおります。
https://derksen.gumroad.com/l/polysource
4.0.6を使用しているのですが、不思議なことに別のPCではpolySourceがオンでもクラッシュしません。
blender4.2.2 Win
よろしくお願いします。

**Comment by mill101** [comment]
追記です。
preview paddingの realtimeチェックボックスです。
よろしくお願いします。

**Comment by mio3io** [comment]
ありがとうございます。
PaddingGuideについては私の方でも問題点が多いと認識しているので、全体的に見直す方向にしたい思います。
