### ISSUE TITLE
Cant find Orient World button

### ISSUE THREAD

**Issue by faxcorp** [mio3io/mio3_uv#9]
https://addon.mio3io.com/#/en/mio3uv/?id=orient-world

How to use this feature? Thanks

**Comment by mio3io** [comment]
This is just using the Z-axis option of Blender's standard functions. Please refer to the Blender manual for instructions on how to use it.

https://docs.blender.org/manual/ja/4.2/modeling/meshes/uv/editing.html?utm_source=blender-4.2.3-lts#bpy-ops-uv-align-rotation
